# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auto test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      

      - name: Setup
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.12'
          version: ${{ env.PDM_VERSION }}
          cache: true
      
      - name: Install dependencies
        run: |
          pdm install
      
      - name: Run pytest
        run: |
          pdm run pytest

